name: Determine Deployment Environment
description: >-
  Determines which environment to deploy templates to
inputs:
  target_branch:
    description: Target repo branch for code push
    required: true
outputs:
  target_environment_name:
    description: Name of the environment to deploy templates
    value: ${{ steps.determine-env.outputs.target_environment_name }}
runs:
  using: composite
  steps:
    - name: Determine Environment
      id: determine-env
      run: |
        if [ ${{ inputs.target_branch }} == 'dev' ]
        then
          echo "::set-output name=target_environment_name::DEV"
        elif [ ${{ inputs.target_branch }} == 'test' ]
        then
          echo "::set-output name=target_environment_name::TEST"
        elif [ ${{ inputs.target_branch }} == 'staging' ]
        then
          echo "::set-output name=target_environment_name::STAGING"
        elif [ ${{ inputs.target_branch }} == 'main' ] || [ ${{ inputs.target_branch }} == 'master' ]
        then
          echo "::set-output name=target_environment_name::PROD"
        fi
      shell: bash