name: Determine Deployment Environment
description: >-
  Determines the target GitHub environment based on the name
  of the branch that code is pushed to
inputs:
  call_target_environment:
    description: Environment to deploy templates in via workflow call
    required: false
outputs:
  target_environment_push:
    description: Name of the environment to deploy templates in via push
    value: ${{ steps.determine-env-push.outputs.target_environment }}
  target_environment_workflow_call:
    description: Name of the environment to deploy templates in via workflow call
    value: ${{ steps.determine-env-workflow-call.outputs.target_environment }}
runs:
  using: composite
  steps:
    - name: Determine Environment via Push
      id: determine-env-push
      if: github.event_name == 'push'
      run: |
        if [ ${{ github.ref_name }} == 'dev' ] || [ ${{ github.ref_name }} == 'test' ] || [ ${{ github.ref_name }} == 'staging' ]
        then
          echo "::set-output name=target_environment_push::${{ github.ref_name }}"
        elif [ ${{ github.ref_name }} == 'main' ] || [ ${{ github.ref_name }} == 'master' ]
        then
          echo "::set-output name=target_environment_push::prod"
        fi
      shell: bash
    - name: Determine Environment via Workflow Call
      id: determine-env-workflow-call
      if: github.event_name == 'workflow_call'
      run: |
        if [ ${{ inputs.call_target_environment }} == 'dev' ] || [ ${{ inputs.call_target_environment }} == 'test' ] || [ ${{ inputs.call_target_environment }} == 'staging' ]
        then
          echo "::set-output name=target_environment_workflow_call::${{ github.ref_name }}"
        elif [ ${{ inputs.call_target_environment }} == 'main' ] || [ ${{ inputs.call_target_environment }} == 'master' ]
        then
          echo "::set-output name=target_environment_workflow_call::prod"
        fi
      shell: bash