name: Determine Deployment Environment
description: >-
  Determines the target GitHub environment based on the name
  of the branch that code is pushed to
outputs:
  target_environment:
    description: Name of the GitHub environment to use for deployment
    value: ${{ steps.determine-env.outputs.target_environment }}
runs:
  using: composite
  steps:
    - name: Determine Environment
      run: |
        if [ ${{ github.ref_name }} == 'dev' ] || [ ${{ github.ref_name }} == 'test' ] || [ ${{ github.ref_name }} == 'staging' ]
        then
          echo "::set-output name=target_environment::${{ github.ref_name }}"
        elif [ ${{ github.ref_name }} == 'main' ] || [ ${{ github.ref_name }} == 'master' ]
        then
          echo "::set-output name=target_environment::prod"
        fi
      shell: bash