name: Test CloudFormation Templates
description: >-
  Tests CloudFormation templates for validity prior to deployment
runs:
  using: composite
  steps:
    - name: Test
      run: |
        make test
      shell: bash