name: Deploy CloudFormation Templates
on:
  push:
    branches:
      - dev
env:
  AWS_REGION : "us-east-1"
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2
jobs:
  test:
    # uses: ${{ github.repository }}/.github/workflows/test.yaml@${{ github.ref_name }}
    uses: ${{ github.repository }}/.github/workflows/test.yaml@dev
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Configure AWS creds
  #       uses: aws-actions/configure-aws-credentials@master
  #       with:
  #         role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT }}:role/managed/GitHubActionsS3ListRole
  #         role-session-name: S3Session
  #         aws-region: ${{ env.AWS_REGION }}
  #     - name: List buckets
  #       run: |
  #         pwd
  #         ls
  #         whoami
  #         python3 -m unittest discover
  #         aws s3 ls