name: Test and Deploy CloudFormation Templates
on:
  push:
    paths:
      - 'templates/*.template'
      - 'config/default.*.json'
permissions:
      id-token: write
      contents: read
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test-cloudformation-templates
  Deploy:
    needs: Test
    if: github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'staging' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Dev
        if: github.ref_name == 'dev'
        uses: ./.github/actions/deploy-cloudformation-templates
        with:
          account-number: ${{ secrets.DEV_ACCOUNT_NUMBER }}
          environment-name: 'dev'
      - name: Deploy to Test
        if: github.ref_name == 'test'
        uses: ./.github/actions/deploy-cloudformation-templates
        with:
          account-number: ${{ secrets.TEST_ACCOUNT_NUMBER }}
          environment-name: 'test'
      - name: Deploy to Staging
        if: github.ref_name == 'staging'
        uses: ./.github/actions/deploy-cloudformation-templates
        with:
          account-number: ${{ secrets.STAGING_ACCOUNT_NUMBER }}
          environment-name: 'staging'
      - name: Deploy to Prod
        if: github.ref_name == 'main'
        uses: ./.github/actions/deploy-cloudformation-templates
        with:
          account-number: ${{ secrets.PROD_ACCOUNT_NUMBER }}
          environment-name: 'prod'